### ISSUE TITLE
CSS doesn't work

### ISSUE THREAD

**Issue by wodecs** [dataCobra/hugo-vitae#27] opened 2020-08-22 10:23 UTC
sorry

**Comment by dataCobra** [comment] 2020-08-24 05:49
Hello @wodecs, the Problem is that you forgot to set the right Link in your configuration of the Website.

In your `config.toml` there is the first row with the following: `baseURL = "http://example.org/"`.

You need to change this to `baseURL = "https://wodecs.github.io/". 

Try this and check if this is a fix for your problem. :slightly_smiling_face: 

Greetings, Ben

**Comment by dataCobra** [comment] 2020-08-26 07:15
Hey @wodecs, is your problem solved?

I would like to close this issue. :slightly_smiling_face: 

Greetings, Ben

**Comment by wodecs** [comment] 2020-08-26 07:18
Alright.

________________________________

**Closed** 2020-08-26 07:30 UTC
